### ISSUE TITLE
incompatibility with Adobe Commerce Cloud

### ISSUE THREAD

**Issue by Dnd-Juver** [wl-online-payments-direct/plugin-magento-core#16]
https://github.com/wl-online-payments-direct/plugin-magento-core/blob/fc9ce260dbbbb495667f3aa6bdf43eeba9fbf88d/Test/Infrastructure/Plugin/Service/Payment/GetPaymentDetailsServiceMock.php#L26

https://github.com/wl-online-payments-direct/plugin-magento-core/blob/fc9ce260dbbbb495667f3aa6bdf43eeba9fbf88d/Test/Infrastructure/Plugin/Service/Payment/GetPaymentDetailsServiceMock.php#L7

````
==> var/log/system.log <==
[2023-02-20T15:33:04.504784+00:00] report.CRITICAL: The specified "/app/245/generated/code/OnlinePayments/Sdk/Domain/PaymentResponseFactory.php.14729" file couldn't be written. Warning!file_put_contents(/app/245/generated/code/OnlinePayments/Sdk/Domain/PaymentResponseFactory.php.14729): Failed to open stream: Read-only file system
Class OnlinePayments\Sdk\Domain\PaymentResponseFactory generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. [] []

==> var/log/debug.log <==
[2023-02-20T15:33:04.504784+00:00] report.CRITICAL: The specified "/app/245/generated/code/OnlinePayments/Sdk/Domain/PaymentResponseFactory.php.14729" file couldn't be written. Warning!file_put_contents(/app/245/generated/code/OnlinePayments/Sdk/Domain/PaymentResponseFactory.php.14729): Failed to open stream: Read-only file system
Class OnlinePayments\Sdk\Domain\PaymentResponseFactory generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. [] []
[2023-02-20T15:33:04.505509+00:00] report.DEBUG: The specified "/app/245/generated/code/OnlinePayments/Sdk/Domain/PaymentResponseFactory.php.14729" file couldn't be written. Warning!file_put_contents(/app/245/generated/code/OnlinePayments/Sdk/Domain/PaymentResponseFactory.php.14729): Failed to open stream: Read-only file system
Class OnlinePayments\Sdk\Domain\PaymentResponseFactory generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. {"exception":"[object] (RuntimeException(code: 0): The specified \"/app/245/generated/code/OnlinePayments/Sdk/Domain/PaymentResponseFactory.php.14729\" file couldn't be written. Warning!file_put_contents(/app/245/generated/code/OnlinePayments/Sdk/Domain/PaymentResponseFactory.php.14729): Failed to open stream: Read-only file system
Class OnlinePayments\\Sdk\\Domain\\PaymentResponseFactory generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. at /app/245/vendor/magento/framework/Code/Generator.php:140)"} []

==> var/log/support_report.log <==
[2023-02-20T15:33:04.526497+00:00] report.CRITICAL: The specified "/app/245/generated/code/OnlinePayments/Sdk/Domain/PaymentResponseFactory.php.14729" file couldn't be written. Warning!file_put_contents(/app/245/generated/code/OnlinePayments/Sdk/Domain/PaymentResponseFactory.php.14729): Failed to open stream: Read-only file system
Class OnlinePayments\Sdk\Domain\PaymentResponseFactory generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. [] []



Next ReflectionException: Impossible to process constructor argument Parameter #1 [ <required> OnlinePayments\Sdk\Domain\PaymentDetailsResponseFactory $paymentDetailsResponseFactory ] of Worldline\PaymentCore\Test\Infrastructure\Plugin\Service\Payment\GetPaymentDetailsServiceMock class in /app/245/vendor/magento/framework/Code/Reader/ClassReader.php:57
Stack trace:
#0 /app/245/vendor/magento/framework/ObjectManager/Definition/Runtime.php(54): Magento\Framework\Code\Reader\ClassReader->getConstructor('Worldline\\Payme...')
#1 /app/245/vendor/magento/framework/ObjectManager/Factory/Compiled.php(100): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Worldline\\Payme...')
#2 /app/245/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create('Worldline\\Payme...')
#3 /app/245/vendor/magento/framework/Interception/PluginList/PluginList.php(174): Magento\Framework\ObjectManager\ObjectManager->get('Worldline\\Payme...')
#4 /app/245/vendor/magento/framework/Interception/Interceptor.php(133): Magento\Framework\Interception\PluginList\PluginList->getPlugin('Worldline\\Payme...', 'Worldline_Payme...')
#5 /app/245/vendor/magento/framework/Interception/Interceptor.php(153): Worldline\PaymentCore\Service\Payment\GetPaymentDetailsService\Interceptor->Magento\Framework\Interception\{closure}('3259532663_0', 1)
#6 /app/245/generated/code/Worldline/PaymentCore/Service/Payment/GetPaymentDetailsService/Interceptor.php(23): Worldline\PaymentCore\Service\Payment\GetPaymentDetailsService\Interceptor->___callPlugins('execute', Array, NULL)
#7 /app/245/vendor/worldline/module-magento-payment-core/Model/Order/ValidatorPool/AcquiredAmountValidator.php(29): Worldline\PaymentCore\Service\Payment\GetPaymentDetailsService\Interceptor->execute('3259532663_0', 1)
#8 /app/245/generated/code/Worldline/PaymentCore/Model/Order/ValidatorPool/AcquiredAmountValidator/Proxy.php(95): Worldline\PaymentCore\Model\Order\ValidatorPool\AcquiredAmountValidator->validate(Object(Worldline\PaymentCore\Model\Order\CanPlaceContext))
#9 /app/245/vendor/worldline/module-magento-payment-core/Model/Order/CanPlaceValidator.php(35): Worldline\PaymentCore\Model\Order\ValidatorPool\AcquiredAmountValidator\Proxy->validate(Object(Worldline\PaymentCore\Model\Order\CanPlaceContext))
#10 /app/245/vendor/worldline/module-magento-payment-core/Model/Webhook/PlaceOrderProcessor.php(125): Worldline\PaymentCore\Model\Order\CanPlaceValidator->validate(Object(Worldline\PaymentCore\Model\Order\CanPlaceContext))
#11 /app/245/vendor/worldline/module-magento-payment-core/Model/Webhook/PlaceOrderProcessor.php(95): Worldline\PaymentCore\Model\Webhook\PlaceOrderProcessor->isValid(Object(OnlinePayments\Sdk\Domain\PaymentResponse), Object(Magento\Quote\Model\Quote\Interceptor))
#12 /app/245/vendor/worldline/module-magento-payment-core/Model/Webhook/GeneralProcessor.php(54): Worldline\PaymentCore\Model\Webhook\PlaceOrderProcessor->process(Object(OnlinePayments\Sdk\Domain\WebhooksEvent))
#13 /app/245/vendor/worldline/module-magento-payment-core/Controller/Webhook/Index.php(74): Worldline\PaymentCore\Model\Webhook\GeneralProcessor->process(Object(OnlinePayments\Sdk\Domain\WebhooksEvent))
#14 /app/245/vendor/magento/framework/Interception/Interceptor.php(58): Worldline\PaymentCore\Controller\Webhook\Index->execute()
#15 /app/245/vendor/magento/framework/Interception/Interceptor.php(138): Worldline\PaymentCore\Controller\Webhook\Index\Interceptor->___callParent('execute', Array)
#16 /app/245/vendor/magento/framework/Interception/Interceptor.php(153): Worldline\PaymentCore\Controller\Webhook\Index\Interceptor->Magento\Framework\Interception\{closure}()
#17 /app/245/generated/code/Worldline/PaymentCore/Controller/Webhook/Index/Interceptor.php(23): Worldline\PaymentCore\Controller\Webhook\Index\Interceptor->___callPlugins('execute', Array, Array)
#18 /app/245/vendor/magento/framework/App/FrontController.php(248): Worldline\PaymentCore\Controller\Webhook\Index\Interceptor->execute()
#19 /app/245/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Worldline\PaymentCore\Controller\Webhook\Index\Interceptor), Object(Magento\Framework\App\Request\Http))
#20 /app/245/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Worldline\PaymentCore\Controller\Webhook\Index\Interceptor))
#21 /app/245/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /app/245/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#23 /app/245/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /app/245/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /app/245/vendor/fastly/magento2/Model/FrontControllerPlugin.php(135): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /app/245/vendor/magento/framework/Interception/Interceptor.php(135): Fastly\Cdn\Model\FrontControllerPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /app/245/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /app/245/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /app/245/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /app/245/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#31 /app/245/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /app/245/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#33 /app/245/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#34 {main} {"report_id":"b5784ff57f411f142ed0d8e34136033abf1a102eb9353f5b3de5ee666484069e"} []
````

**Comment by WorldlineMagentoTeam** [comment]
Hello, @Dnd-Juver . Thank you for the feedback. Please, verify on the latest 2.7.0 version.
